version: '3.8'
services:
  microservice-one:
    build:
      context: ./microservice-one
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8081"
  microservice-two:
    build:
      context: ./microservice-two
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8082"
  microservice-three:
    build:
      context: ./microservice-three
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8083:8083"
